DROP TABLE IF EXISTS TASK_SCHEDULER;
CREATE TABLE TASK_SCHEDULER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  cron_expression VARCHAR(250) NOT NULL,
  client_name VARCHAR(250) NOT NULL,
  config_1 VARCHAR(250) DEFAULT NULL,
  config_2 VARCHAR(250) DEFAULT NULL
);